name: Upload Artifact 

on:
  push:
   branches: 
       - main

jobs:
  build:
   runs-on: ubuntu-latest

   steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with: 
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Npm test
        run: npm test

      - name: Npm lint 
        run: npm run lint

   
